version: 2
jobs:
  build:
    docker:
      - image: koop4/nodeawscli:latest
    working_directory: "~/universitech"
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run: npm install
      - save_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
          paths:
            - ./node_modules
      - run: npm run build
      - run: npm audit fix
      - run: aws s3 rm s3://univeritech --recursive
      - run: aws s3 cp dist s3://univeritech --recursive
      #- run: aws s3 cp sitemap.xml s3://univeritech
      - run: aws cloudfront create-invalidation --distribution-id EPG88TOGLI4DY --paths "/*"
  nothing:
    docker:
      - image: koop4/nodeawscli:latest
    working_directory: "~/universitech"
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run: npm install
      - save_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
          paths:
            - ./node_modules
      - run: npm run build
workflows:
  version: 2
  build-deploy:
    jobs:
      - nothing:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              only:
                - master